name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - id: build-publish
      uses: bitovi/github-actions-storybook-to-github-pages@upgrade-child-actions
      with:
          path: storybook-static
          # want a separate workflow, required prod build to generate type definition
          build_command: npm run build && npm run build-storybook